### ISSUE TITLE
Evaluate timing in periodic tests

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/che-functional-tests#468]
We should track how long the different steps of the Che periodic tests are currently taking. 

In particular we should track how long it takes to bootstrap a Che workspace, to clone a project and to build it. For bootstrapping we should evaluate the time of the single startup phases as it has already been done by @amisevsk when evaluating the bottlenecks (@amisevsk any hint to help QE team to do it would be useful).

The work may be subdivided in 4 steps:

- [x] **STEP1** Evaluate the global time for Che workspaces bootstrap #467
- [ ] **STEP2** Evaluate the elapsed time for all the phases of the workspaces bootstrap: #501
  - [ ] Plugin broker start
  - [ ] Plugin broker processing
  - [ ] Marked as starting
  - [ ] Pull eclipse/che-dev:nightly
  - [ ] Pull wsskeleton/che-machine-exec
  - [ ] Pull wsskeleton/che-hello
  - [ ] Pull eclipse/che-theia:plugin-id-nightly
  - [ ] Workspace containers all running
  - [ ] Theia start
  - [ ] Start completed
- [ ] **STEP3** Evaluate the elapsed time to clone a project
- [ ] **STEP4** Evaluate the elapsed time to build a project
- [ ] **STEP5** Use last 7 days timing results to evaluate the delta with current build (using a weighted average of last 7 days)   

As a result the new report would look as this:

|environment	| cluster |	status | timing | comment |
| --- | --- | --- | --- | --- |
|production	| us-east-2   | 	passing | ws-start: 30s (-5%)</br>clone: 20s (-5%)</br>build:	10s (-5%)|  |
|production	| us-east-2a | 	passing | ws-start: 30s (-5%)</br>clone: 20s (-5%)</br>build:	10s (-5%)|  |
|production	| us-east-1a |	passing | ws-start: 30s (-5%)</br>clone: 20s (-5%)</br>build:	10s (-5%)|  |
|production	| us-east-1b |	passing | ws-start: 30s (-5%)</br>clone: 20s (-5%)</br>build:	10s (-5%)|  |
|prod-preview	| us-east-2a |	passing | ws-start: 30s (-5%)</br>clone: 20s (-5%)</br>build:	10s (-5%)|  |

**Comment by Katka92** [comment]
Cool, thank you for detailed description. Just a question about the percentage in ```timing``` column - what is that supposed to mean? Is that comparison with previous report?

**Comment by l0rd** [comment]
@Katka92 good question. I would say we should compare the current result with last 7 days weighted averages. Let me add STEP 5 for that.

**Comment by Katka92** [comment]
Just for following, once related issue about adding some workspace metrics: https://github.com/eclipse/che/issues/13270

**Comment by Katka92** [comment]
The issue was moved. Closing.
